In [1]:
import torch
import numpy as np


https://pytorch.org/docs/stable/tensors.html

# *class* torch.Tensor

There are a few main ways to create a tensor, depending on your use case.

* To create a tensor with pre-existing data, use torch.tensor()

* To create a tensor with specific size, use torch.* tensor creation ops

* To create a tensor with the same size (and similar types) as another tensor, use torch.*_like tensor creation ops

* To create a tensor with similar type but different size as another tensor, use tensor.new_* creation ops

In [65]:
# all tensors are instances of torch.Tensor

t = torch.tensor([1.0, 2.0, 3.0])
print(type(t))
isinstance(t, torch.Tensor)

<class 'torch.Tensor'>


True

In [47]:
# since dtype is torch.float32, t is also instance of torch.FloatTensor 

isinstance(t, torch.FloatTensor), isinstance(t, torch.LongTensor)

(True, False)

In [42]:
# torch.FloatTensor is not inherit torch.Tensor

issubclass(torch.FloatTensor, torch.Tensor)

False

In [158]:
# create tensors of particular size with __call__

torch.Tensor(2,3)

tensor([[1.2686e-34, 0.0000e+00, 1.4091e-34],
        [0.0000e+00, 7.9717e-10, 1.0524e+21]])

torch.Tensor is an alias for the default tensor type (torch.FloatTensor)

# torch.tensor(data)

https://pytorch.org/docs/stable/generated/torch.tensor.html

    torch.tensor(data) always creates a **copy** of data with no autograd history!!

In [ ]:
# 3 parameters for torch.tensor()

TENSOR = torch.tensor([1,2,3], dtype=torch.float32,
                               device='cpu',
                               requires_grad=False)

In [84]:
data = np.array([1,2,3])
t = torch.tensor(data)

data[0] = 100

print(data)
print(t)        # t is a copy

[100   2   3]
tensor([1, 2, 3])


## Avoid Making Copies

### 1. torch.as_tensor(data)

https://pytorch.org/docs/stable/generated/torch.as_tensor.html#torch.as_tensor

Converts data into a tensor, **sharing data** and preserving autograd history if possible

If data is a NumPy array with the same dtype and device then a tensor is constructed using torch.from_numpy()

In [149]:
data = np.array([1,2,3])
t = torch.as_tensor(data)

data[0] = 100

t   # shares data and not a copy

tensor([100,   2,   3])

If data is a tensor or ndarray(NumPy) with a different dtype or device then it’s **copied** as if using data.to(dtype=dtype, device=device)

    Change of device or dtype always results in a copy

In [150]:
data1 = torch.tensor(([1,2,3]))
data2 = np.array([1,2,3])

t1 = torch.as_tensor(data1, dtype=torch.float16)
t2 = torch.as_tensor(data2, dtype=torch.float16)

data1[0], data2[0] = 100, 100

t1, t2   # both are copy

(tensor([1., 2., 3.], dtype=torch.float16),
 tensor([1., 2., 3.], dtype=torch.float16))

### 2. torch.from_numpy(data)

https://pytorch.org/docs/stable/generated/torch.from_numpy.html#torch.from_numpy

Creates a Tensor from a numpy.ndarray. The returned tensor and ndarray **share the same memory**

In [3]:
data = np.array([1,2,3])
t = torch.from_numpy(data)

data[0] = 100

print(t)    # shares data and not a copy

tensor([100,   2,   3])


# Tensor Attributes

https://pytorch.org/docs/stable/tensor_attributes.html#tensor-attributes-doc

1. dtype

2. device

3. layout

In [6]:
TENSOR = torch.tensor([1,2,3], dtype=torch.float32,
                               device='cpu',
                               requires_grad=False)

## 1. torch.dtype

In [60]:
ht = torch.tensor([1.5, 2.1, 3.0], dtype=torch.float16)
ht
print('dtype:', ht.dtype)

dtype: torch.float16


In [61]:
# 정수형 tensor에서 default dtype은 torch.int64

it = torch.tensor([1,2,3])
print(it)
print('dtype:', it.dtype)

tensor([1, 2, 3])
dtype: torch.int64


In [62]:
# 실수형 tensor에서 default dtype은 torch.float32

ft = torch.tensor([1.5, 2.1, 3.0])
print(ft)
print('dtype:', ft.dtype)

tensor([1.5000, 2.1000, 3.0000])
dtype: torch.float32


### calculating bet. different dtypes

check official document of Tensor Attributes

## 2. torch.device

check official document of Tensor Attributes for further detail

In [94]:
device = torch.device('cpu')
t = torch.tensor([1,2,3], device=device)

print('current device:', t.device)

current device: cpu


## 3. torch.layout

torch.layout is an object that represents the memory layout of a torch.Tensor.

Currently, 1. torch.strided (dense Tensors) is supported and have beta support for 2. torch.sparse_coo (sparse COO Tensors)

torch.strided represents dense Tensors. Each strided tensor has an associated torch.Storage, which holds its data. The tensor class provides multi-dimensional, strided view of a storage

In [117]:
t = torch.arange(0, 12).view(3,4)
tT = t.T


print(t)
print('layout:', t.layout)
print('storage:', t.storage())
print('stride:', t.stride())

print('-' * 50)

print(tT)
print('layout:', tT.layout)
print('storage:', tT.storage())
print('stride:', tT.stride())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
layout: torch.strided
storage:  0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 12]
stride: (4, 1)
--------------------------------------------------
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
layout: torch.strided
storage:  0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 12]
stride: (1, 4)


## Changing dtype and device

all methods for changing dtypes and device make a **copy**

In [51]:
# changing dtype

it = torch.tensor([1,2,3])
print('original tensor before change:', it)

# 1. torch.Tensor.type()
ft1 = it.type(torch.float32)    # copy

# 2.  torch.Tensor.float()
ft2 = it.float()                # copy

# 3. torch.Tensor.to()
ft3 = it.to(torch.float32)      # copy


it[0] = 100

print('original tensor after change:', it)
print('tensor ft1:', ft1)
print('tensor ft2:', ft2)
print('tensor ft3:', ft3)

original tensor before change: tensor([1, 2, 3])
original tensor after change: tensor([100,   2,   3])
tensor ft1: tensor([1., 2., 3.])
tensor ft2: tensor([1., 2., 3.])
tensor ft3: tensor([1., 2., 3.])


In [132]:
# changing device

t = torch.tensor([1,2,3], device='cpu')

# t.to('cuda')      # copy

# etc

## requires_grad

In [155]:
t = torch.tensor([1., 2., 3.], requires_grad=True)
print('requires grad:', t.requires_grad)

t.requires_grad_(False)     # change requires_grad
print('requires grad:', t.requires_grad)

requires grad: True
requires grad: False


## torch.Tensor.item()

In [159]:
t = torch.tensor(1)
t, t.item()

(tensor(1), 1)