In [2]:
import torch

# Tensor Arithmetric Operations

## Addition

In [14]:
M = torch.eye(3,3)

print('matrix M:\n', M)
print('-' * 50)
print('matrix M + 1:\n', M + 1)
print('-' * 50)
print('matrix M + 1:\n', M.add(1))
print('-' * 50)
print('matrix M + 1:\n', torch.add(M, 1))
print('-' * 50)
print('matrix M:\n', M)     # original matrix didn't change

matrix M:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
--------------------------------------------------
matrix M + 1:
 tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])
--------------------------------------------------
matrix M + 1:
 tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])
--------------------------------------------------
matrix M + 1:
 tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])
--------------------------------------------------
matrix M:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [17]:
print('matrix M + 1:\n', M.add_(1))     # inplace operation
print('-' * 50)
print('matrix M:\n', M)     # original matrix changed

matrix M + 1:
 tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])
--------------------------------------------------
matrix M:
 tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])


## Subtraction

In [22]:
M = torch.eye(3,3)

print('matrix M:\n', M)
print('-' * 50)
print('matrix M - 1:\n', M - 1)
print('-' * 50)
print('matrix M - 1:\n', M.sub(1))
print('-' * 50)
print('matrix M - 1:\n', torch.sub(M, 1))
print('-' * 50)
print('matrix M:\n', M)     # original matrix didn't change

matrix M:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
--------------------------------------------------
matrix M - 1:
 tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])
--------------------------------------------------
matrix M - 1:
 tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])
--------------------------------------------------
matrix M - 1:
 tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])
--------------------------------------------------
matrix M:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [23]:
print('matrix M - 1:\n', M.sub_(1))     # inplace operation
print('-' * 50)
print('matrix M:\n', M)     # original matrix changed

matrix M - 1:
 tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])
--------------------------------------------------
matrix M:
 tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])


## Multiplication

In [24]:
M = torch.eye(3,3)

print('matrix M:\n', M)
print('-' * 50)
print('matrix M * 2:\n', M * 2)
print('-' * 50)
print('matrix M * 2:\n', M.mul(2))
print('-' * 50)
print('matrix M * 2:\n', torch.mul(M, 2))
print('-' * 50)
print('matrix M:\n', M)     # original matrix didn't change

matrix M:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
--------------------------------------------------
matrix M * 2:
 tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])
--------------------------------------------------
matrix M * 2:
 tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])
--------------------------------------------------
matrix M * 2:
 tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])
--------------------------------------------------
matrix M:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [25]:
print('matrix M * 2:\n', M.mul_(2))     # inplace operation
print('-' * 50)
print('matrix M:\n', M)     # original matrix changed

matrix M * 2:
 tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])
--------------------------------------------------
matrix M:
 tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])


## Division

In [27]:
M = torch.eye(3,3)

print('matrix M:\n', M)
print('-' * 50)
print('matrix M / 2:\n', M / 2)
print('-' * 50)
print('matrix M / 2:\n', M.div(2))
print('-' * 50)
print('matrix M / 2:\n', torch.div(M, 2))
print('-' * 50)
print('matrix M:\n', M)     # original matrix didn't change

matrix M:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
--------------------------------------------------
matrix M / 2:
 tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.5000]])
--------------------------------------------------
matrix M / 2:
 tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.5000]])
--------------------------------------------------
matrix M / 2:
 tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.5000]])
--------------------------------------------------
matrix M:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [29]:
print('matrix M / 2:\n', M.div_(2))     # inplace operation
print('-' * 50)
print('matrix M:\n', M)     # original matrix changed

matrix M / 2:
 tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.5000]])
--------------------------------------------------
matrix M:
 tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.5000]])


## Matrix Multiplication

### 1. Matrix @ Matrix

output is a 2-dim. tensor (matrix)

In [39]:
M = torch.randn(3,4)
N = torch.randn(4,2)

print('matrix M shape:', M.shape)
print('matrix N shape:', N.shape)
print('-' * 50)

# 1 torch.matmul(M, N)
print('M @ N shape:', torch.matmul(M, N).shape)

# 2 M.matmul(N)
print('M @ N shape:', M.matmul(N).shape)

# 3 torch.mm(M, N)
print('M @ N shape:', torch.mm(M, N).shape)

# 4 M.mm(N)
print('M @ N shape:', M.mm(N).shape)

# 5 M @ N
print('M @ N shape:', (M @ N).shape)

matrix M shape: torch.Size([3, 4])
matrix N shape: torch.Size([4, 2])
--------------------------------------------------
M @ N shape: torch.Size([3, 2])
M @ N shape: torch.Size([3, 2])
M @ N shape: torch.Size([3, 2])
M @ N shape: torch.Size([3, 2])
M @ N shape: torch.Size([3, 2])


### 2. Matrix @ Vector

output is a 1-dim. tensor (vector)

In [38]:
M = torch.randn(3,4)
v = torch.randn(4)

print('matrix M shape:', M.shape)
print('vector v shape:', v.shape)
print('-' * 50)

# 1 torch.matmul(M, v)
print('M @ v shape:', torch.matmul(M, v).shape)

# 2 M.matmul(v)
print('M @ v shape:', M.matmul(v).shape)

# 3 torch.mv(M, v)
print('M @ v shape:', torch.mv(M, v).shape)

# 4 M.mv(v)
print('M @ v shape:', M.mv(v).shape)

# 5 M @ v
print('M @ v shape:', (M @ v).shape)

matrix M shape: torch.Size([3, 4])
vector v shape: torch.Size([4])
--------------------------------------------------
M @ v shape torch.Size([3])
M @ v shape torch.Size([3])
M @ v shape torch.Size([3])
M @ v shape torch.Size([3])
M @ v shape torch.Size([3])


### 3. Vector @ Matrix

output is a 1-dim. tensor (vector)

In [69]:
v = torch.randn(3)
M = torch.randn(3,4)

print('vector v shape:', v.shape)
print('matrix M shape:', M.shape)
print('-' * 50)

# 1 torch.matmul(v, M)
print('v @ M shape:', torch.matmul(v, M).shape)

# 2 v.matmul(M)
print('v @ M shape:', v.matmul(M).shape)

# 3 M @ v
print('v @ M shape:', (v @ M).shape)

vector v shape: torch.Size([3])
matrix M shape: torch.Size([3, 4])
--------------------------------------------------
v @ M shape: torch.Size([4])
v @ M shape: torch.Size([4])
v @ M shape: torch.Size([4])


### 4. Vector @ Vector

output is a 0-dim. tensor (scalar)

In [70]:
v = torch.randn(3)
w = torch.randn(3)

print('vector v shape:', v.shape)
print('vector w shape:', w.shape)
print('-' * 50)

# 1 torch.matmul(v, w)
print('v @ w shape:', torch.matmul(v, w).shape)

# 2 v.matmul(M)
print('v @ w shape:', v.matmul(w).shape)

# 3 M @ v
print('v @ w shape:', (v @ w).shape)

vector v shape: torch.Size([3])
vector w shape: torch.Size([3])
--------------------------------------------------
v @ w shape: torch.Size([])
v @ w shape: torch.Size([])
v @ w shape: torch.Size([])


### 5. Tensor @ Matrix

In [73]:
M = torch.randn(5,3,4)
N = torch.randn(4,2)

print('tensor M shape:', M.shape)
print('matrix N shape:', N.shape)
print('-' * 50)

# 1 torch.matmul(M, N)
print('M @ N shape:', torch.matmul(M, N).shape)

# 2 M.matmul(N)
print('M @ N shape:', M.matmul(N).shape)

# 3 M @ N
print('M @ N shape:', (M @ N).shape)

tensor M shape: torch.Size([5, 3, 4])
matrix N shape: torch.Size([4, 2])
--------------------------------------------------
M @ N shape: torch.Size([5, 3, 2])
M @ N shape: torch.Size([5, 3, 2])
M @ N shape: torch.Size([5, 3, 2])


### 5. Matrix @ Tensor

In [75]:
M = torch.randn(3,4)
N = torch.randn(5,4,2)

print('matrix M shape:', M.shape)
print('tensor N shape:', N.shape)
print('-' * 50)

# 1 torch.matmul(M, N)
print('M @ N shape:', torch.matmul(M, N).shape)

# 2 M.matmul(N)
print('M @ N shape:', M.matmul(N).shape)

# 3 M @ N
print('M @ N shape:', (M @ N).shape)

matrix M shape: torch.Size([3, 4])
tensor N shape: torch.Size([5, 4, 2])
--------------------------------------------------
M @ N shape: torch.Size([5, 3, 2])
M @ N shape: torch.Size([5, 3, 2])
M @ N shape: torch.Size([5, 3, 2])


### Conclusion

stick to **torch.matmul** or **@** which can be widely applied