In [159]:
import torch

# Tensor Views

https://pytorch.org/docs/stable/tensor_view.html

In [158]:
t = torch.arange(10)
M = t.view(2,5)

print('base tensor:', t)
print('view tensor:', M)

print('same data memory:', t.data_ptr() == M.data_ptr())    # view tensor shares the same underlying data with its base tensor. 

M[0,0] = 100    # Modifying view tensor changes base tensor as well
print('base tensor:', t)
print('view tensor:', M)

base tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
view tensor: tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
same data memory: True
base tensor: tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])
view tensor: tensor([[100,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


## contiguous tensors

In [100]:
M = torch.arange(8).reshape(2,4)
Mt = M.t()
Mt2 = Mt.contiguous()   # enforce copying data when `Mt` is not contiguous to get contiguous tensor

print('Mt contiguous:', Mt.is_contiguous())
print('Mt2 contiguous:', Mt2.is_contiguous())
print('-' * 50)

print('tensor Mt:\n', Mt)
print('tensor Mt2:\n', Mt2)   # same data
print('-' * 50)

print('Mt storage:', Mt.storage())
print('Mt2 storage:', Mt2.storage())    # layout changed to make tensor contiguous

Mt contiguous: False
Mt2 contiguous: True
--------------------------------------------------
tensor Mt:
 tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])
tensor Mt2:
 tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])
--------------------------------------------------
Mt storage:  0
 1
 2
 3
 4
 5
 6
 7
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 8]
Mt2 storage:  0
 4
 1
 5
 2
 6
 3
 7
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 8]


# view()

https://pytorch.org/docs/stable/generated/torch.Tensor.view.html

In [111]:
M = torch.randn(2,4)
M_view = M.view(4,2)

print('M contiguous:', M.is_contiguous())
print('same memory:', M.data_ptr() == M_view.data_ptr())    # view

M contiguous: True
same memory: True


In [112]:
Mt = M.t()  # .t() returns view

print('Mt contiguous:', Mt.is_contiguous())

Mt_view = Mt.view(2,2,2)  # in this case, view is created although Mt is not contiguous
print('same memory:', M.data_ptr() == Mt_view.data_ptr())

Mt.view(2,4)    # cannot create view

Mt contiguous: False
same memory: True


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

# reshape()

https://pytorch.org/docs/stable/generated/torch.reshape.html

    returns view if possible, else returns copy

In [116]:
M = torch.randn(2,4)
M_reshape = M.reshape(4,2)

print('same memory:', M.data_ptr() == M_reshape.data_ptr())     # view

same memory: True


In [117]:
Mt = M.t()  # .t() returns view
Mt_reshape = Mt.reshape(2,4)

print('same memory:', M.data_ptr() == Mt_reshape.data_ptr())    # copy

same memory: False


# permute()

https://pytorch.org/docs/stable/generated/torch.permute.html#torch.permute

    returns view

In [119]:
M = torch.randn(2, 3, 5)

print('tensor M shape:', M.size())
print('tensor M shape after permute:', M.permute(2,0,1).size())

tensor M shape: torch.Size([2, 3, 5])
tensor M shape after permute: torch.Size([5, 2, 3])


# transpose()

https://pytorch.org/docs/stable/generated/torch.transpose.html#torch.transpose

    returns view if input is strided tensor

In [125]:
M = torch.randn(2, 3, 5)

print('tensor M shape:', M.size())
print('tensor M shape after transpose:', M.transpose(0,1).size())

tensor M shape: torch.Size([2, 3, 5])
tensor M shape after transpose: torch.Size([3, 2, 5])


# T

    returns view

In [120]:
M = torch.randn(2, 3, 5)

print('tensor M shape:', M.size())
print('tensor M shape after T:', M.T.size())    # equivalent to M.permute(n-1, n-2, ..., 0)

tensor M shape: torch.Size([2, 3, 5])
tensor M shape after T: torch.Size([5, 3, 2])


# mT

    returns view

In [134]:
M = torch.randn(2, 3, 5)

print('tensor M shape:', M.size())
print('tensor M shape after mT:', M.mT.size())

tensor M shape: torch.Size([2, 3, 5])
tensor M shape after mT: torch.Size([2, 5, 3])


# squeeze() / unsqueeze()

https://pytorch.org/docs/stable/generated/torch.squeeze.html

https://pytorch.org/docs/stable/generated/torch.unsqueeze.html

    returns view

In [36]:
M = torch.randn(3,1,2,1,4)

print('tensor M shape:', M.shape)
print('tensor M shape after squeeze:', M.squeeze().shape)
print('tensor M shape after squeeze of given dim:', M.squeeze(dim=1).shape)
print('tensor M shape:', M.shape)   # doesn't change original tensor

tensor M shape: torch.Size([3, 1, 2, 1, 4])
tensor M shape after squeeze: torch.Size([3, 2, 4])
tensor M shape after squeeze of given dim: torch.Size([3, 2, 1, 4])
tensor M shape: torch.Size([3, 1, 2, 1, 4])


In [46]:
M = torch.randn(3,2,4)

print('tensor M shape:', M.shape)
print('tensor M shape after unsqueeze:', M.unsqueeze(dim=1).shape)
print('tensor M shape:', M.shape)   # doesn't change original tensor

tensor M shape: torch.Size([3, 2, 4])
tensor M shape after unsqueeze: torch.Size([3, 1, 2, 4])
tensor M shape: torch.Size([3, 2, 4])


# split()

https://pytorch.org/docs/stable/generated/torch.split.html#torch.split

    returns view

In [160]:
M = torch.randn(10,3)

M.split(4, dim=0)    # split size

(tensor([[-0.5643, -1.7106,  0.4178],
         [-0.5787,  1.6969, -1.0581],
         [ 0.6216, -0.3524,  1.4452],
         [ 1.5583,  0.2216,  0.8427]]),
 tensor([[-0.3251,  0.2625, -0.9964],
         [ 1.6694, -0.3952,  0.5485],
         [-0.4208,  1.3071,  0.4308],
         [ 1.0798, -0.7649,  0.1510]]),
 tensor([[-0.4081,  0.2047, -0.1016],
         [-0.3021, -0.1500,  0.0825]]))

In [163]:
M = torch.randn(10,3)

M.split([1,4,5], dim=0)    # split section

(tensor([[-0.0736, -0.3137, -0.2389]]),
 tensor([[ 0.5531, -1.6912, -0.7959],
         [-0.8158,  0.1184, -1.0938],
         [-1.5594,  2.0082, -0.5666],
         [-0.0358, -1.0796, -1.0379]]),
 tensor([[ 0.5899, -1.0051, -0.3351],
         [-0.8898,  1.0382,  1.1405],
         [ 0.5793, -0.5514,  1.3916],
         [ 0.2950, -0.6828,  0.7144],
         [ 0.6035, -0.8606, -0.2066]]))

# chunk()

https://pytorch.org/docs/stable/generated/torch.chunk.html#torch.chunk

    returns view

In [169]:
M = torch.randn(10,3)

M.chunk(4, dim=0)   # number of chuncks

(tensor([[ 0.2341, -1.7935,  0.2225],
         [-0.8964, -0.3458, -0.9920],
         [ 0.1107, -2.5733,  0.7776]]),
 tensor([[ 0.3252, -2.0168,  1.3477],
         [-0.1625, -0.1699, -0.0067],
         [ 2.7201,  0.1987, -1.7251]]),
 tensor([[ 1.0358,  1.9285,  0.4576],
         [ 1.3377,  0.8691, -1.6527],
         [ 0.2574, -1.0060,  0.1165]]),
 tensor([[1.0916, 0.0541, 1.2650]]))

# stack()

https://pytorch.org/docs/stable/generated/torch.stack.html

In [174]:
M = torch.randn(3,4)
N = torch.randn(3,4)

t = torch.stack((M, N), dim=0)

print('tensor M shape:', M.shape)
print('tensor N shape:', N.shape)
print('tensor t shape:', t.shape)   # makes new dimension

tensor M shape: torch.Size([3, 4])
tensor N shape: torch.Size([3, 4])
tensor t shape: torch.Size([2, 3, 4])


# cat()

https://pytorch.org/docs/stable/generated/torch.cat.html

In [146]:
M = torch.randn(3,4)
N = torch.randn(3,4)

t = torch.cat((M, N), dim=0)

print('tensor M shape:', M.shape)
print('tensor N shape:', N.shape)
print('tensor t shape:', t.shape)   # concatenated along dim

tensor M shape: torch.Size([3, 4])
tensor N shape: torch.Size([3, 4])
tensor t shape: torch.Size([6, 4])
