In [5]:
import torch
import torch.nn as nn
import numpy as np
import gudhi
import sys

In [58]:
# for [1, 28, 28] image: lims = [[1, -1], [-1, 1]], by= [-1/13.5, 1/13.5]
# for [3, 28, 28] image: lims = [[-1, 1], [1, -1], [-1, 1]], by= [1, -1/13.5, 1/13.5]

def grid_by(lims=[[1,-1], [-1,1]], shape=(28,28)):
    """
    Creates a tensor of grid points with shape [(C*H*W), D]
    Grid points have one-to-one correspondnce with pixel values flattened in row-major order
    
    * D = 2 if 1-channel or D=3 if 3-channel

    Args:
        lims: [domain of C, domain of H, domain of W] if C > 1 or [domain of H, domain of W] if 1-channel
        size: (C, H, W) if C > 1 or (H, W) if 1-channel
    """
    assert len(shape) in (2,3) and len(lims) == len(shape)
    expansions = [torch.linspace(start, end, step) for (start, end), step in zip(lims, shape)]
    print(expansions)
    grid_size = [len(ex) for ex in expansions]  # [H, W] if 1-channel or [C, H, W] if 3-channel
    grid = torch.index_select(torch.cartesian_prod(*expansions),
                              dim=1,
                              index=torch.tensor([0,2,1]) if len(lims)==3 else torch.tensor([1,0]))
    return grid, grid_size


grid, grid_size = grid_by(lims = [[-1, 1], [1, -1], [-1, 1]], shape=(10,2,3))


[tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000]), tensor([ 1., -1.]), tensor([-1.,  0.,  1.])]


In [ ]:
torch.linspace()

In [65]:
x = torch.zeros(2,3,4)
y = torch.zeros(3,4)
x.shape[1:]

torch.Size([3, 4])

In [8]:
x = np.arange(3*4*5).reshape(3,4,5)
y = np.arange(6*5).reshape(5,6)
z = np.dot(x, y)
z.shape

(3, 4, 6)

In [38]:
x = torch.rand(784)
x = torch.where(x<0.7, 0, x)
cub_cpx = gudhi.CubicalComplex(dimensions=[28,28], top_dimensional_cells=x)
ph = cub_cpx.persistence(homology_coeff_field=2, min_persistence=0)
loc = cub_cpx.cofaces_of_persistence_pairs()

In [52]:
loc[0][0]

array([], shape=(0, 2), dtype=int64)

In [11]:
y = torch.zeros(3,4)
y[:1]

tensor([[0., 0., 0., 0.]])

In [16]:
x = torch.ones(2, requires_grad=True)
y = torch.zeros(2, requires_grad=True)
z = x * y

In [19]:
print(z.grad_fn)

In [87]:
x, y, z

(tensor([1., 1.], requires_grad=True),
 tensor([0., 0.]),
 tensor([0., 0.], grad_fn=<MulBackward0>))

In [88]:
x.is_leaf, y.is_leaf, z.is_leaf

(True, True, False)

In [94]:
dir(z.grad_fn)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_raw_saved_other',
 '_raw_saved_self',
 '_register_hook_dict',
 '_saved_other',
 '_saved_self',
 'metadata',
 'name',
 'next_functions',
 'register_hook',
 'register_prehook',
 'requires_grad']

In [95]:
c = torch.tensor(1)
c.data_ptr()

116752448

In [98]:
c = c + 1
c.data_ptr()

116630720